version: '3.8'
services:
  sqlserver-db:
    user: root
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment:
      SA_PASSWORD: Admin12345**
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/sqlserver/data
